import { post } from '@/client';
import {
  assertTransactionHash,
  TransactionOutcomeUnknownError,
  TransactionSubmissionError
} from './errors';

import type {
  AuthorizedTxV2,
  OperationName
} from '@/signing/v2';

function extractHash(
  value: unknown
): string | undefined {
  if (
    typeof value !== 'object' ||
    value === null
  ) {
    return undefined;
  }
  const hash = (value as { hash?: unknown }).hash;
  return typeof hash === 'string'
    ? hash
    : undefined;
}

// A REST-layer 408 (l1client crates/api/om-api-rest/src/infra/mod.rs
// `timeout` middleware) is generated by a `tokio::time::timeout` racing
// the *entire* request
// handler -- including the pool-admission call -- against a 10s
// clock. If admission wins that race a hair too late, the middleware
// still discards the result and answers 408: unlike every other 4xx
// below (which the handler returns synchronously, before it ever
// calls into the pool), a 408 can genuinely follow a successful
// admission. It is therefore excluded from the refused bucket below
// and falls through to "unknown" like any other 5xx.
const AMBIGUOUS_CLIENT_ERROR_STATUS = 408;

// A value shaped like ParsedError (src/client/core.ts): a numeric
// HTTP status plus the response body the node actually sent back
// (`data`). Requiring `data` to be present -- not just a numeric
// `status` -- keeps a resolved client-side timeout out of this
// bucket: parseError() defaults a timeout's status to 500 too, but a
// timeout never has a `data`, since no response body ever arrived.
// That case is genuinely ambiguous and belongs in the "unknown"
// outcome below, not "refused".
//
// Only 4xx (except 408, see above) counts as refused. l1client's REST
// layer (om-api-types/src/rest/error.rs `get_status_code`,
// om-api-types/src/native/error.rs `http_status_code`) returns every
// 4xx -- validation, resource-not-found, read-only-node,
// domain-separated-signature-not-active, rate-limit -- synchronously,
// before the request ever reaches pool submission. Every 5xx
// (`SystemDatabaseError`/`SystemNetworkError`/`SystemServiceError`/
// `SystemConfigError`, all mapped from the same `ApiError` family
// that also includes `PoolError` -- the pool's own admission
// rejection) collapses into one opaque "system error" bucket the
// client cannot distinguish from a failure downstream of admission,
// and a 502/503/504 in front of the node (ALB/nginx/Cloudflare) can
// just as easily follow a successful admission as precede one. So a
// 5xx can never be trusted as "not submitted" -- it belongs in the
// "unknown" outcome below, alongside 408.
function isRefusedResponse(
  value: unknown
): value is {
  status: number;
  message?: string;
  data?: unknown;
} {
  if (
    typeof value !== 'object' ||
    value === null
  ) {
    return false;
  }
  const v = value as {
    status?: unknown;
    data?: unknown;
  };
  return (
    typeof v.status === 'number' &&
    v.status >= 400 &&
    v.status < 500 &&
    v.status !== AMBIGUOUS_CLIENT_ERROR_STATUS &&
    v.data !== undefined &&
    extractHash(value) === undefined
  );
}

// core.ts's login branch (src/client/core.ts, the
// `rules.login?.(...)` branches in both the `.then` and `.catch`
// arms of `request()`) resolves with just the response body -- the
// numeric HTTP status is discarded before it ever reaches
// submitAuthorized. `isRefusedResponse` above can therefore never
// match a refused write that arrived this way (e.g. a WAF/gateway
// 401 in front of the node), even though it is exactly as
// pre-admission as any other 4xx: nothing reaches a WAF-refused
// request's body past the gateway, let alone the node's pool.
//
// The status is gone, so this keys off the one thing left: the body
// shape `isLogin` itself matches (src/client/index.ts:
// `res.code == 401`, loose equality intentionally mirrored below).
// Deliberately narrower than isRefusedResponse -- it does not also
// accept a `status` field, since a value with a numeric `status`
// either already matched isRefusedResponse above or was correctly
// excluded (408/5xx/2xx).
function isLoginRefusalBody(
  value: unknown
): value is {
  data?: unknown;
  msg?: unknown;
} {
  if (
    typeof value !== 'object' ||
    value === null ||
    extractHash(value) !== undefined
  ) {
    return false;
  }
  const v = value as { code?: unknown };
  // Loose equality is intentional -- mirrors isLogin's `res.code ==
  // 401` (src/client/index.ts), which matches both the number 401
  // and the string '401'.
  return v.code == 401;
}

function unknownOutcomeDiagnostic(
  value: unknown
): {
  status?: number;
  data?: unknown;
  cause?: unknown;
} {
  if (
    typeof value !== 'object' ||
    value === null
  ) {
    return { cause: value };
  }
  const result = value as {
    status?: unknown;
    data?: unknown;
  };
  return {
    status:
      typeof result.status === 'number'
        ? result.status
        : undefined,
    data: result.data,
    cause: value
  };
}

// POST an authorized v2 transaction and classify the outcome into
// three, deliberately distinct cases:
//
// 1. Hash-bearing success -- the node returned a string `hash`.
//    Verify it, fail-closed, against the locally computed
//    transactionHash. See TransactionHashMismatchError for why a
//    mismatch here is not retryable.
// 2. Refused -- the node (or a gateway/WAF in front of it) rejected
//    the write before it ever reached the pool: a 4xx (other than
//    408, see isRefusedResponse) with a response body, or the
//    body-only 401 shape isLoginRefusalBody detects once core.ts's
//    login branch has stripped the status. NOT submitted; safe to
//    retry once the underlying cause is fixed. See
//    TransactionSubmissionError.
// 3. Unknown -- neither of the above (e.g. a timeout, a network
//    error, a 5xx/408, or a 2xx body with no hash). The node may or
//    may not have admitted the transaction; do not guess either way.
//    See TransactionOutcomeUnknownError.
//
// `post()`'s promise wrapper RESOLVES instead of REJECTS whenever the
// caller configured a global `onError`/`onTimeout` via
// `setInitConfig` (see core.ts's `existedHandler.error`/`.timeout`
// branches) -- so the exact same ParsedError-shaped value can arrive
// either as a caught rejection or as a "successful" resolution.
// Both are routed through the classification below instead of
// trusting resolve-vs-reject to mean success-vs-failure, which is
// what let a refused write masquerade as a submitted one.
export async function submitAuthorized<
  T extends { hash: string }
>(
  authorized: AuthorizedTxV2,
  expectedOperation: OperationName
): Promise<T> {
  if (authorized.operation !== expectedOperation) {
    throw new Error(
      `[1Money SDK]: Expected a "${expectedOperation}" authorization but received "${authorized.operation}". Refusing to submit -- prepare and authorize the transaction with the matching TransactionBuilder method.`
    );
  }

  let response: unknown;
  try {
    response = await post<'custom', unknown>(
      authorized.path,
      authorized.request,
      { withCredentials: false }
    );
  } catch (caught) {
    response = caught;
  }

  const hash = extractHash(response);
  if (hash !== undefined) {
    assertTransactionHash(
      authorized.transactionHash,
      hash
    );
    return response as T;
  }

  if (isRefusedResponse(response)) {
    throw new TransactionSubmissionError(
      response.status,
      response.data,
      typeof response.message === 'string'
        ? response.message
        : 'the node rejected the request'
    );
  }

  if (isLoginRefusalBody(response)) {
    throw new TransactionSubmissionError(
      401,
      response.data,
      typeof response.msg === 'string'
        ? response.msg
        : 'the node returned a 401 (unauthorized) response'
    );
  }

  throw new TransactionOutcomeUnknownError(
    authorized.transactionHash,
    unknownOutcomeDiagnostic(response)
  );
}
